### ISSUE TITLE
[BUG] Wrong letter rendering

### ISSUE THREAD

**Issue by entnuo** [FoedusProgramme/Gramophone#362] opened 2024-12-26 21:15 UTC
**Describe the bug**
Gramophone is rendering `ê` as `ę` even though the file name shows the correct accent.

**To Reproduce**
1. Open gramophone
2. Scroll down to the music

**Expected behavior**
Show `ê` as it is.

**Note:** for some reason is just this music (at least that I found with this bug). There's another song titled "Tous les mêmes" and the `ê` is rendered correctly.

**Screenshots**
![1735246978865](https://github.com/user-attachments/assets/4c0a13b0-0f11-409e-9912-ef4b5ccc40b3)

**Smartphone:**
 - Device: Redmi Note 12 S
 - OS: Android 14
 - App Version: 1.0.15.64ab51

**Additional context**
There's none.

- [x] I will open one issue per bug, follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment] 2024-12-26 21:29
I believe this is caused by https://issuetracker.google.com/issues/237674422 and hence will be a "won't fix: external issue". LMK if you disagree / can't follow.

**Closed as not planned by nift4** 2024-12-26 21:29 UTC
Labels: need confirm

**Comment by entnuo** [comment] 2024-12-26 21:33
That's fine, I didn't know about that issue, thought it was gramophone's bug and opened this issue. Sorry for inconvenience.

Have a nice day/night.
