### ISSUE TITLE
[BUG] Release year label in flac format cannot be read

### ISSUE THREAD

**Issue by dacancc** [FoedusProgramme/Gramophone#43] opened 2023-11-29 03:13 UTC
Describe the bug
Release year label in flac format cannot be read

Expected behavior
Can correctly read flac tags and add sorting function

Form Version [1.0.2.d9fc41]

**Comment by AkaneTan** [comment] 2023-11-29 18:52
https://github.com/kabouzeid/Phonograph/issues/740
Mentioned here. Seems like a mediastore bug and can be reproduced here.
Probably will do a special handling in the future but not now.

**Comment by nift4** [comment] 2024-01-31 13:44
This cannot be fixed by us. You need to ask your phone OEM's support, because we rely on information provided to us by your phone OS, and we have no plans of changing that.

**Closed as completed by nift4** 2024-01-31 13:44 UTC
Labels: bug, help wanted
