### ISSUE TITLE
Can't set this app as a default music player on Xiaomi device.

### ISSUE THREAD

**Issue by TaseenCR** [FoedusProgramme/Gramophone#190] opened 2024-05-29 13:31 UTC
On my Xiaomi Redmi device which is currently running on HyperOS based on Android 14, I can't set it as a default music player. It doesn't appear in the select app list while other foss music player apps can be seen there just right.

**To Reproduce**
1. Go to Settings> Apps> Default apps.
2. Click on default music player app.
3. This app is not in the list.

**Expected behavior**
I should be able to choose Gramophone as a default music player app.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 12
 - OS: Android 14
 - App Version: 1.0.5

**Comment by fukiame** [comment] 2024-05-29 13:32
duplicate of #136

**Closed as not planned** 2024-05-31 17:37 UTC
Labels: need confirm
