### ISSUE TITLE
[BUG] Audio skipping during playback of ACC codec .m4a format

### ISSUE THREAD

**Issue by PixelCode5** [FoedusProgramme/Gramophone#6] opened 2023-09-11 08:56 UTC
**Audio skipping during playback of ACC codec .m4a format**

Some of my .m4a format audio file skipping/shuttering during playback. It is strange some audio with same codec works just fine. I checked if specific audio file was corrupted in case, but with native audio player it seems to play just fine. I have provided below some logs during specific event when audio skips happen. Could be just related to my old outdated hardware/codec. I hope there is way to troubleshoot this.

**Expected behavior**
A Smooth playback without any shutter of audio.

**Logcat Details**

```
11.09 14:13:23.865 10138 952 952 com.android.systemui V/MediaTimeout: processState: PlaybackState {state=3, position=6295, buffered position=64505, speed=1.0, updated=47267352, actions=7340031, custom actions=[Action:mName='Shuffle, mIcon=2131165386, mExtras=Bundle[EMPTY_PARCEL], Action:mName='Close, mIcon=2131165340, mExtras=Bundle[EMPTY_PARCEL]], active item id=26, error=null}
11.09 14:13:24.282 1046 555 17703 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
11.09 14:13:24.283 1046 555 17703 W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence
11.09 14:13:24.666 1046 555 17703 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
11.09 14:13:24.666 1046 555 17703 W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence

11.09 14:13:25.048 1041 465 570 W/APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1

11.09 14:13:25.585 1046 555 17703 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
11.09 14:13:25.585 1046 555 17703 W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence

11.09 14:13:25.971 1046 555 17703 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
11.09 14:13:25.971 1046 555 17703 W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence
11.09 14:13:26.322 10212 17148 17702 org.akanework.gramophone D/CCodecBuffers: [c2.android.aac.decoder#20:1D-Input.Impl[N]] codec released a buffer owned by client (index 3)
11.09 14:13:26.326 10212 17148 17702 org.akanework.gramophone D/CCodecBuffers: [c2.android.aac.decoder#20:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
11.09 14:13:26.869 10138 952 952 com.android.systemui V/MediaTimeout: processState: PlaybackState {state=3, position=9294, buffered position=64505, speed=1.0, updated=47270357, actions=7340031, custom actions=[Action:mName='Shuffle, mIcon=2131165386, mExtras=Bundle[EMPTY_PARCEL], Action:mName='Close, mIcon=2131165340, mExtras=Bundle[EMPTY_PARCEL]], active item id=26, error=null}

11.09 14:13:31.669 10212 17148 17702 org.akanework.gramophone D/CCodecBuffers: [c2.android.aac.decoder#20:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
11.09 14:13:31.678 10212 17148 17702 org.akanework.gramophone D/CCodecBuffers: [c2.android.aac.decoder#20:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
11.09 14:13:32.179 1046 555 17703 W/C2SoftAacDec: aacDecoder_DecodeFrame decoderErr = 0x4004
11.09 14:13:32.179 1046 555 17703 W/C2SoftAacDec: AAC decoder returned error 0x4004, substituting silence
11.09 14:13:32.186 10212 17148 17702 org.akanework.gramophone D/CCodecBuffers: [c2.android.aac.decoder#20:1D-Input.Impl[N]] codec released a buffer owned by client (index 2)
11.09 14:13:32.464 1046 555 17703 D/BufferPoolAccessor2.0: bufferpool2 0xb3939418 : 6(24576 size) total buffers - 1(4096 size) used buffers - 14552/14558 (recycle/alloc) - 91/14557 (fetch/transfer)
11.09 14:13:32.499 10212 17148 17164 org.akanework.gramophone I/work.gramophon: Background young concurrent copying GC freed 51887(1918KB) AllocSpace objects, 12(2592KB) LOS objects, 23% free, 14MB/18MB, paused 176us total 116.912ms
```

**Smartphone info:**
 - Device: 
          SDK: 30
          PRODUCT_NAME: hlte
          DEVICE_NAME: hlte
          BOARD_NAME: MSM8974
          SUPPORTED_ABIS: armeabi-v7a, armeabi
          MANUFACTURER: samsung
          BRAND: samsung
          MODEL: SM-N9005
- OS: [Lineage OS based on Android 11]

**Comment by AkaneTan** [comment] 2023-09-11 09:12
Can you send the audio file that causes skipping?

**Comment by AkaneTan** [comment] 2023-09-11 14:58
Confirmed with my own device, need to look into it.

**Comment by AkaneTan** [comment] 2023-09-11 15:10
@AkaneTan https://github.com/google/ExoPlayer/issues/9058
Seems relevant. Not gramophone's issue since we haven't done anything to the decoder (We're using default decoder for media3 in this case). "Should be fixed with an OEM update" is quite suspicious. It's rather a codec2 bug or a blob bug, but anyways I'll blame google on that one :)

**Closed as completed** 2023-09-11 15:10 UTC
Labels: bug, wontfix
