### ISSUE TITLE
Allow deleting songs

### ISSUE THREAD

**Issue by JulioCabria** [FoedusProgramme/Gramophone#194] opened 2024-06-02 10:21 UTC
**Is your feature request related to a problem? Please describe.**

We all sometimes find songs and audio files that arent music, like old voice notes, recordings, etc that we want deleted. The process now is to identify the file name, open a file explorer, navigate to the file and delete it.

It would be nice to have a "Delete" option for each song so you can delete them from Gramophone directly.

**Describe the solution you'd like**

Tap the three dots to the right of a song and tap a new "Delete" option to delete that song from disk.

**Describe alternatives you've considered**

Using a file manager does the job, but because Gramophone displays audio files from different locations, you first have to inspect the song to get the location and then travel to it.

This solution requires using an additional app (file explorer) and finding the song twice.

**Additional context**

Mockup for the requested "Delete" entry:

![IMG-20240602-WA0001](https://github.com/AkaneTan/Gramophone/assets/72270024/6a3be6ed-7895-43a2-ade5-9f3336726924)

**Comment by nift4** [comment] 2024-06-02 10:30
duplicate of #133 and planned

**Closed as not planned by nift4** 2024-06-02 10:30 UTC
Labels: enhancement
