### ISSUE TITLE
Ability to create playlists inside app

### ISSUE THREAD

**Issue by yuw1xx** [FoedusProgramme/Gramophone#186] opened 2024-05-27 10:29 UTC
I think it would be great if there was a feature where you can create playlists. Or the app could detect folders and show them as playlists. I think this feature would be very appreciated, at least by me.

**Comment by nift4** [comment] 2024-05-27 10:31
The app detects m3u files. Adding an editor is planned and duplicate of #27

**Closed as not planned by nift4** 2024-05-27 10:31 UTC
Labels: enhancement
