### ISSUE TITLE
Ability to delete songs directly from the app

### ISSUE THREAD

**Issue by sanjeethboddi** [FoedusProgramme/Gramophone#331] opened 2024-12-02 04:04 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- [ ] I will open one issue per request, follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment] 2024-12-02 09:51
1. you did not fill the template
2. you did not follow the title format
3. this issue is a duplicate of #133

**Closed as not planned by nift4** 2024-12-02 09:51 UTC
Labels: enhancement
