### ISSUE TITLE
[BUG] Album cover does not show up

### ISSUE THREAD

**Issue by MetroDelta** [FoedusProgramme/Gramophone#73] opened 2024-01-04 03:39 UTC
**Describe the bug**
The album cover does not show up if I manually add it trough a software like Mp3tag.

**To Reproduce**
1. Download an audio file 
2. Attribute an image to the album cover to the file with a software such as Mp3tag 
3. Send the audio file to the phone
4. Play the audio file on Gramophone

**Expected behavior**
I expected the album cover to show up, but it only show up on the lock screen or the toolbar at the top.

**Screenshots**
![Screenshot_20240104-043012.png](https://github.com/AkaneTan/Gramophone/assets/59743605/59acc216-19cb-497b-8c46-1692a430583b)

![Screenshot_20240104-043021~2.png](https://github.com/AkaneTan/Gramophone/assets/59743605/61d4f148-5674-4cb8-9d5d-d2658d683946)

![Screenshot_20240104-043027~2.png](https://github.com/AkaneTan/Gramophone/assets/59743605/613c42e8-2ad1-44ee-85b4-2cd8c82b2b59)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]

**Smartphone (please complete the following information):**
 - Device: [Pixel 7]
 - OS: [Android 14]
 - Browser [Cromite]
 - Version [120.0.6099.144]

**Comment by AkaneTan** [comment] 2024-01-04 05:12
Can't reproduce on my device. Maybe try clearing the app data?

**Comment by MetroDelta** [comment] 2024-01-04 05:26
> Can't reproduce on my device. Maybe try clearing the app data?

I tried, but for unknown reasons, it didn't work.

**Comment by nift4** [comment] 2024-01-04 09:38
which gramophone version?

**Comment by MetroDelta** [comment] 2024-01-04 10:46
> which gramophone version?

My version is 1.0.2.a13566.

**Comment by MetroDelta** [comment] 2024-01-05 08:26
I'm not sure how useful this additional information can be, but another thing I've noticed was that when I tried to replicate it on the other apps, the problem recurred on only one other app, which is SongSync from Lambada10. All the others, whether it's VLC, Musicolet, Oto Music or Vanilla Music Player by Kyant, displayed the cover normally.
![Screenshot_20240105-091846.png](https://github.com/AkaneTan/Gramophone/assets/59743605/cdccfede-b9f4-4d87-a28c-4de3bd6ab15f)
![Screenshot_20240104-192230.png](https://github.com/AkaneTan/Gramophone/assets/59743605/ae01c222-6921-4860-9d7e-08b658a9a68d)

![Screenshot_20240104-064548.png](https://github.com/AkaneTan/Gramophone/assets/59743605/02b3644b-dc02-434c-bb1d-a7216ee1a821)

![Screenshot_20240104-064442.png](https://github.com/AkaneTan/Gramophone/assets/59743605/8f987047-67cc-4b3b-a6a0-dcd47afb3764)

**Comment by nift4** [comment] 2024-01-05 08:34
yes this information is useful, it means MediaStore cannot extract cover but media3 can. The disparity is because notification being handled directly by media3. The bug here is that we do not display MediaStore version in notification, and the fact that Android does not recognize the album cover in the way you added it is an inherent Android limitation. (Why can other music players show it then? They scan all audio files on start-up, we rely on what Android told us, an key difference)

**Comment by AkaneTan** [comment] 2024-01-11 13:27
Closing this as it's a non-reproducable problem
P.S. very likely it's asker's system's problem

**Closed as completed by AkaneTan** 2024-01-11 13:27 UTC
Labels: can't reproduce
