### ISSUE TITLE
Playlist [BUG]

### ISSUE THREAD

**Issue by rezalef** [FoedusProgramme/Gramophone#170] opened 2024-04-28 05:00 UTC
**Describe the bug**
Can't Change and Modify Playlists.

**To Reproduce**
Go to 'Playlists Tab'

**Smartphone:**
 - Device: Xiaomi 13T
 - OS: HyperOS (Android 14)
 - App Version: 1.0.5

**Comment by nift4** [comment] 2024-04-28 06:12
Duplicate of #27

**Closed as not planned by nift4** 2024-04-28 06:12 UTC
Labels: need confirm
