### ISSUE TITLE
[FR] Replay Gain support

### ISSUE THREAD

**Issue by TTsdzb** [FoedusProgramme/Gramophone#227] opened 2024-07-18 06:42 UTC
**Is your feature request related to a problem? Please describe.**
Normally, different music has different loudness, thus the user may have to adjust volume frequently due to loudness difference. [ReplayGain](https://en.wikipedia.org/wiki/ReplayGain) is designed to solve this issue by unify playback loudness.

**Describe the solution you'd like**
Read `REPLAYGAIN_TRACK_GAIN` and `REPLAYGAIN_ALBUM_GAIN` metadata tag, automatically attenuate or amplify the signal.

**Describe alternatives you've considered**
None

**Additional context**
May be designed as a optional feature in "Audio" settings.

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by AkaneTan** [comment] 2024-07-18 08:46
Duplicate of #122

**Closed as completed by AkaneTan** 2024-07-18 08:46 UTC
Labels: enhancement
